### ISSUE TITLE
Yaw in trajectory

### ISSUE THREAD

**Issue by kevin-thankyou-lin** [icsl-Jeon/traj_gen2-matlab#1]
Hi, thanks for the nice code base :)

Does the generated trajectory specify the **yaw** of the quadrotor too?
If not, would you have any ideas on how to do so?

**Comment by kennethhoffmann** [comment]
As far as I can tell, it only provides position/velocity/etc points. What I've done is set the yaw to be the tangent to the position points.

**Comment by kevin-thankyou-lin** [comment]
Got it - thanks!
